---
- name: Configure global settings.
  ansible.builtin.lineinfile:
    dest: "{{ _postgresql_config_path }}/postgresql.conf"
    regexp: "^#?{{ item.option }}.+$"
    line: "{{ item.option }} = '{{ item.value }}'"
    state: "{{ item.state | default('present') }}"
    mode: '0644'
  loop: "{{ postgresql_autotune_config_options |
    community.general.lists_mergeby(postgresql_global_config_options, 'option') |
    community.general.lists_mergeby(postgresql_global_config_options_extra, 'option') }}"
  # notify: Restart postgresql
  notify: Reload postgresql

- name: Configure host based authentication (if entries are configured).
  ansible.builtin.template:
    src: "{{ postgresql_hba_template_path }}"
    dest: "{{ _postgresql_config_path }}/pg_hba.conf"
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    backup: true
    mode: "600"
  diff: true
  # notify: Restart postgresql
  notify: Reload postgresql
# Not using the postgresql_hba module because it entailed having
# a task to ensure the file is empty of default rules
# a task to add the rules.
# The first task should only be executed once otherwise the rules
# task will also always report as changed which is not true.
# Basically it added more complications whilst the template module
# works just fine.

- name: Ensure PostgreSQL unix socket dirs exist.
  ansible.builtin.file:
    path: "{{ item }}"
    state: directory
    owner: "{{ postgresql_user }}"
    group: "{{ postgresql_group }}"
    mode: "{{ _postgresql_unix_socket_directories_mode }}"
  loop: "{{ postgresql_unix_socket_directories }}"

- name: Ensure PostgreSQL permissions are persisted accross reboots
  ansible.builtin.template:
    src: "{{ postgresql_tempfile_src_template_path }}"
    dest: "{{ postgresql_tempfile_dest_path }}"
    owner: "{{ postgresql_tempfile_owner }}"
    group: "{{ postgresql_tempfile_group }}"
    mode: "{{ postgresql_tempfile_mode }}"
  when: postgresql_persist_permissions

- name: Set postgresql service enabled state
  ansible.builtin.service:
    name: "{{ _postgresql_daemon }}"
    enabled: "{{ postgresql_service_enabled }}"

- name: Ensure postgresql service is running with latest up to date configuration
  ansible.builtin.meta: flush_handlers

- name: Retrieve settings requiring a restart
  community.postgresql.postgresql_query:
    query: select name from pg_settings where pending_restart='true';
    port: "{{ postgresql_port }}"
    login_user: "{{ postgresql_user }}"
    login_unix_socket: "{{ postgresql_unix_socket_directories[0] }}"
  register: _postgresql_res_pending_params
  # changed_when: _postgresql_res_pending_params.rowcount > 0
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
    ansible_python_interpreter: "{{ _postgresql_ansible_python_interpreter }}"

- name: Handle params requiring a full restart to be taken into account
  when: _postgresql_res_pending_params.rowcount > 0
  block:
    - name: Extract param names
      ansible.builtin.set_fact:
        _postgresql_pending_params_str: "'{{ _postgresql_res_pending_params.query_result | map(attribute='name') | list | join(',') }}'"

    - name: Display params awaiting restart
      when: not postgresql_config_change_allow_restart
      ansible.builtin.debug:
        msg: >-
          The following configuration parameters are pending a restart for their new values to take effect:
          {{ _postgresql_pending_params_str }}.

          To enable a full service restart (which may cause downtime), set
          `postgresql_config_change_allow_restart` to `true`.

    - name: Restart service
      when: postgresql_config_change_allow_restart
      ansible.builtin.service:
        name: "{{ _postgresql_daemon }}"
        state: restarted
