---
- name: Manage extensions.
  community.postgresql.postgresql_ext:
    name: "{{ item.name }}"
    db: "{{ item.db }}"
    state: "{{ item.state | d('present') }}"
    schema: "{{ item.schema | d('public') }}"
    cascade: "{{ item.cascade | d(omit) }}"
    version: "{{ item.version | d(omit) }}"
    trust_input: "{{ item.trust_input | d(omit) }}"
    # connection options
    ca_cert: "{{ postgresql_conn_vars.ca_cert | d(omit, true) }}"
    connect_params: "{{ postgresql_conn_vars.connect_params | d(omit, true) }}"
    login_host: "{{ postgresql_conn_vars.login_host | d(omit, true) }}"
    login_password: "{{ postgresql_conn_vars.login_password | d(omit, true) }}"
    login_unix_socket: "{{ postgresql_conn_vars.login_unix_socket | d(omit, true) }}"
    login_user: "{{ postgresql_conn_vars.login_user | d(omit, true) }}"
    login_port: "{{ postgresql_conn_vars.login_port | d(omit, true) }}"
    session_role: "{{ postgresql_conn_vars.session_role | d(omit, true) }}"
    ssl_cert: "{{ postgresql_conn_vars.ssl_cert | d(omit, true) }}"
    ssl_key: "{{ postgresql_conn_vars.ssl_key | d(omit, true) }}"
    ssl_mode: "{{ postgresql_conn_vars.ssl_mode | d(omit, true) }}"
  register: _ext_mgmt_res
  changed_when:
    - _ext_mgmt_res.changed
    - not(item.state | d('present') == 'present' and item.version | d('') == 'latest')
  loop: "{{ postgresql_extensions }}"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
    ansible_python_interpreter: "{{ _postgresql_ansible_python_interpreter }}"
