---
- name: Manage extensions.
  community.postgresql.postgresql_ext:
    name: "{{ item.name }}"
    db: "{{ item.db }}"
    login_host: "{{ item.login_host | default('localhost') }}"
    login_password: "{{ item.login_password | default(omit) }}"
    login_user: "{{ item.login_user | default(postgresql_user) }}"
    login_unix_socket: "{{ item.login_unix_socket | default(postgresql_unix_socket_directories[0]) }}"
    port: "{{ postgresql_port }}"
    state: "{{ item.state | d('present') }}"
    schema: "{{ item.schema | d('public') }}"
    # allow usage of all options
    ssl_mode: "{{ item.ssl_mode | d(omit) }}"
    ca_cert: "{{ item.ca_cert | d(omit) }}"
    session_role: "{{ item.session_role | d(omit) }}"
    cascade: "{{ item.cascade | d(omit) }}"
    version: "{{ item.version | d(omit) }}"
    trust_input: "{{ item.trust_input | d(omit) }}"
  register: _ext_mgmt_res
  changed_when:
    - _ext_mgmt_res.changed
    - not(item.state | d('present') == 'present' and item.version | d('') == 'latest')
  loop: "{{ postgresql_extensions }}"
  become: true
  become_user: "{{ postgresql_user }}"
  vars:
    ansible_ssh_pipelining: true
    ansible_python_interpreter: "{{ _postgresql_ansible_python_interpreter }}"
