---
# Variable configuration.
- name: Setup variables
  ansible.builtin.import_tasks: setup-vars.yml
  tags: always

- name: Include uninstallation tasks
  ansible.builtin.include_tasks:
    file: uninstall.yml
    apply:
      tags: uninstallation
  tags: uninstallation
  when: postgresql_uninstall_1 | bool and postgresql_uninstall_2 | bool

- name: Import installation tasks
  ansible.builtin.import_tasks: install.yml
  tags:
    - install
    - installation

- name: Import initialization tasks
  ansible.builtin.import_tasks: initialize.yml
  tags:
    - init
    - initialize
    - initialise

- name: Import auto tunning tasks
  ansible.builtin.import_tasks: autotune.yml
  when: postgresql_autotune | bool
  tags:
    - auto-tune
    - autotune

- name: Import configuration tasks
  ansible.builtin.import_tasks: configure.yml
  tags:
    - config
    - configure
    - configuration

- name: Import primary replication tasks
  ansible.builtin.import_tasks: replication-primary.yml
  when:
    - postgresql_replication
    - postgresql_replication_role == "primary"
  tags:
    - repli
    - replication

- name: Import replica replication tasks
  ansible.builtin.import_tasks: replication-replica.yml
  when:
    - postgresql_replication
    - postgresql_replication_role == "replica"
  tags:
    - repli
    - replication

- name: Import backup tasks
  ansible.builtin.import_tasks: backup.yml
  when: postgresql_backup | bool
  tags: backup

- name: Import user management tasks
  ansible.builtin.import_tasks: users.yml
  when: not postgresql_replication or postgresql_replication_role == "primary"
  tags:
    - user
    - users

- name: Import tablespace tasks
  ansible.builtin.import_tasks: tablespaces.yml
  tags:
    - tblspc
    - tablespace
    - tablespaces

- name: Import databases tasks
  ansible.builtin.import_tasks: databases.yml
  when: not postgresql_replication or postgresql_replication_role == "primary"
  tags:
    - db
    - database
    - databases

- name: Import ownerships and privileges tasks
  ansible.builtin.import_tasks: ownerships.yml
  when: not postgresql_replication or postgresql_replication_role == "primary"
  tags:
    - owner
    - owners
    - ownership
    - priv
    - privs
    - privileges

- name: Import extensions tasks
  ansible.builtin.import_tasks: extensions.yml
  when: not postgresql_replication or postgresql_replication_role == "primary"
  tags:
    - ext
    - extension
    - extensions

- name: Import sql script and queries tasks
  ansible.builtin.import_tasks: sql.yml
  when: not postgresql_replication or postgresql_replication_role == "primary"
  tags:
    - query
    - script
