---
- name: Gather OS specific variables
  ansible.builtin.include_vars: "{{ loop_vars }}"
  loop: "{{ query('ansible.builtin.first_found', params) }}"
  vars:
    params:
      files:
        - "{{ ansible_distro | lower }}-{{ ansible_distro_version }}.yml"
        - "{{ ansible_distro | lower }}-{{ ansible_distro_release }}.yml"
        - "{{ ansible_distro | lower }}-{{ ansible_distro_major_version }}.yml"
        - "{{ ansible_distro | lower }}.yml"
        - "{{ ansible_os_family | lower }}-{{ ansible_distro_major_version }}-family.yml"
        - "{{ ansible_os_family | lower }}-family.yml"
        - "{{ ansible_system | lower }}.yml"
      paths:
        - "vars"
      skip: true
  loop_control:
    loop_var: loop_vars

- name: "Build proxy environnement to enable/disable proxy use for general internet usage and package manager actions"
  ansible.builtin.set_fact:
    _postgresql_general_proxy_env:
      http_proxy: "{{ postgresql_http_general_proxy | d(omit, true) }}"
      https_proxy: "{{ postgresql_https_general_proxy | d(omit, true) }}"
    _postgresql_pkg_proxy_env:
      http_proxy: "{{ postgresql_http_pkg_proxy | d(omit, true) }}"
      https_proxy: "{{ postgresql_https_pkg_proxy | d(omit, true) }}"

- name: Add relication hba rules
  ansible.builtin.set_fact:
    _postgresql_replication_hba_entries: "{{ _postgresql_replication_hba_entries | d([]) +
      [{'contype': 'host', 'databases': 'replication', 'users': postgresql_replication_user, 'address': item, 'method': postgresql_replication_auth_method}]
      }}"
  loop: "{{ postgresql_replication_replica_addresses }}"
  when:
    - postgresql_replication
    - postgresql_replication_hba_entries | d([], true) | length == 0
