- name: Retrieve THP kernel setting path
  ansible.builtin.find:
    paths: /sys/kernel/mm
    patterns: .*transparent_hugepage
    file_type: directory
    use_regex: true
  register: _postgresql_kernel_thp_find_res


- name: Ensure THP state :{{ postgresql_thp_state }}
  when: _postgresql_kernel_thp_find_res.matched == 1
  block:
    - name: Export THP kernel files path
      ansible.builtin.set_fact:
        _postgresql_thp_kernel_path: '{{ _postgresql_kernel_thp_find_res.files[0].path }}'

    # Return a file if it contains the desired state
    - name: Check if THP defrag is in desired state:{{ postgresql_thp_state }}
      ansible.builtin.find:
        paths: /sys/kernel/mm/transparent_hugepage
        patterns: enabled
        contains: '.*\[{{ postgresql_thp_state }}\]'
      register: _postgresql_thp_defrag_check_res

    - name: Check THP is in desired state:{{ postgresql_thp_state }}
      ansible.builtin.lineinfile:
        path: "{{ _postgresql_thp_kernel_path }}/enabled"
        regexp: ".*\\[{{ postgresql_thp_state }}\\]"
        state: absent
      check_mode: true
      changed_when: false
      register: _postgresql_thp_check_res

    - name: Ensure THP defrag is:{{ postgresql_thp_defrag_state }}
      ansible.builtin.command:
        cmd: tee {{ _postgresql_thp_kernel_path }}/defrag
        stdin: "{{ postgresql_thp_state }}"
      become: true
      become_user: root
      changed_when: true
      when: _postgresql_thp_defrag_check_res.matched == 0

    - name: Ensure THP is:{{ postgresql_thp_state }}
      ansible.builtin.command:
        cmd: tee {{ _postgresql_thp_kernel_path }}/enabled
        stdin: "{{ postgresql_thp_state }}"
      become: true
      become_user: root
      when: _postgresql_thp_check_res.found == 0
      changed_when: true

    - name: Persist THP state (non debian based distros)
      when:
        - ansible_os_family | lower != 'debian'
        - postgresql_thp_persistent_state
      block:
        - name: Copy systemd service
          ansible.builtin.template:
            src: etc/systemd/system/manage-thp.service.j2
            dest: /etc/systemd/system/manage-thp.service
            owner: root
            group: root
            mode: '0644'
          notify: Reload systemd

        - name: Force systemd reload
          ansible.builtin.meta: flush_handlers

        - name: Ensure service is enabled and started
          ansible.builtin.service:
            name: manage-thp
            enabled: true

    - name: Persist THP state (debian based distros)
      when:
        - ansible_os_family | lower == 'debian'
        - postgresql_thp_persistent_state
      block:
        - name: Install sysfsutils
          ansible.builtin.apt:
            name: sysfsutils
            state: present

        - name: Ensure sysfs.conf exists
          ansible.builtin.file:
            path: /etc/sysfs.conf
            owner: root
            group: root
            mode: "0644"

        - name: Ensure THP is disabled in file
          ansible.builtin.lineinfile:
            path: /etc/sysfs.conf
            line: kernel/mm/transparent_hugepage/enabled = never
