---
- name: Drop virtual environment with pip dependencies
  ansible.builtin.file:
    path: "{{ _postgresql_virtualenv_path }}"
    state: absent

- name: Remove backup directory
  ansible.builtin.file:
    path: "{{ postgresql_backup_root_dir }}"
    state: absent

- name: Remove backup cron job
  ansible.builtin.cron:
    name: "{{ postgresql_backup_cron_job_name }}"
    state: absent

- name: Stop postgresql service
  ansible.builtin.systemd:
    name: "{{ _postgresql_daemon }}"
    state: stopped
    enabled: false

- name: Import tasks (debian/uninstall.yml)
  ansible.builtin.import_tasks: debian/uninstall.yml
  when: ansible_os_family | lower == "debian"

- name: Import tasks (redhat/uninstall.yml)
  ansible.builtin.import_tasks: redhat/uninstall.yml
  when: ansible_os_family | lower == "redhat"

- name: Delete the permissions tmpfiles.d config
  ansible.builtin.file:
    path: "{{ postgresql_tempfile_dest_path }}"
    state: absent
  when: postgresql_persist_permissions

- name: Delete data dir
  ansible.builtin.file:
    path: "{{ _postgresql_data_dir }}"
    state: absent

- name: Delete tablespace location
  ansible.builtin.file:
    path: "{{ item.location }}"
    state: absent
  when: item.location | d('') != ''
  loop: "{{ postgresql_tablespaces }}"

- name: End play after uninstallation
  ansible.builtin.meta: end_play
