---
dependency:
  name: shell
  command: "${MOLECULE_SCENARIO_DIRECTORY}/tools/install-dependencies"

driver:
  name: docker

platforms:
  # On "${name:-${image:-debian}", the last brace does not miss, it works like that...
  # The env var should be used when the image variable refers to a full registry path like registry.access.redhat.com/ubi8/ubi
  - &default
    # name: claranet_postgresql_${name:-${image:-debian}-${tag:-latest}-${scenario:-default}${postgresql_version}
    name: claranet-postgresql-default-latest
    image: ${image:-debian}:${tag:-latest}
    privileged: true
    tty: true
    volumes:
      - "/sys/fs/cgroup:/sys/fs/cgroup:rw"
      - "/var/run/docker.sock:/var/run/docker.sock:ro"
    stop_signal: "SIGRTMIN+3"
    capabilities:
      - SYS_ADMIN
      - SYS_TIME
      - LINUX_IMMUTABLE
    command: "/lib/systemd/systemd"
    cgroupns_mode: host

provisioner:
  name: ansible
  env:
    ANSIBLE_FORCE_COLOR: "true"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "true"
    ANSIBLE_STDOUT_CALLBACK: "ansible.posix.debug"
    ANSIBLE_CALLBACKS_ENABLED: "ansible.posix.profile_tasks"
  options:
    v: true
  ansible_args:
    - -v
    - --tags=always,uninstall,install,init,autotune,config,repli,backup,vacuum,user,tablespace,db,owner,ext,query
  inventory:
    group_vars:
      all:
        postgresql_debug: true
        postgresql_version: ${postgresql_version:-15}


verifier:
  name: ansible

lint: |
  set -e
  yamllint .
  ansible-lint
