---
- name: Remove all postgresql packages
  ansible.builtin.dnf:
    name: "{{ _postgresql_packages | select('match', 'postgresql') }}"
    state: absent

- name: Uninstall postgresql rpm repository
  ansible.builtin.dnf:
    name: "{{ _postgresql_repo_rpm_package }}"
    state: absent
  environment: "{{ _postgresql_pkg_proxy_env }}"
